In [1]:
import torch

### 초기화를 하지 않은 비어있는 8x4 matrix를 만들어 보세요

* 0차원 tensor ->스칼라
* 1차원 tensor -> 벡터
* 2차원 tensor -> 행렬
* 3차원 이상의 tensor -> tensor

In [2]:
x = torch.empty(8, 4)

In [3]:
x

tensor([[4.3605e+27, 2.8929e+12, 7.5338e+28, 1.8037e+28],
        [3.4740e-12, 1.7743e+28, 6.8239e+16, 1.8832e+34],
        [1.6078e+19, 4.4721e+21, 5.0789e-11, 4.4721e+21],
        [1.0986e+27, 7.1854e+22, 3.0573e+32, 1.8469e+25],
        [5.1931e-11, 7.0367e+22, 2.4032e+20, 1.6928e+22],
        [2.7945e+20, 2.2419e+20, 3.2532e+33, 3.3028e-12],
        [7.0789e+31, 4.2964e+24, 5.5261e+31, 4.2964e+24],
        [2.7254e+20, 1.8179e+31, 2.8298e+20, 3.0304e+35]])

In [4]:
# 모델적합을 위해서는 shape이 항상 일치해야 한다!!
x.shape

torch.Size([8, 4])

In [7]:
x = torch.empty(8, 4)
print(x.shape)

torch.Size([8, 4])


# Note

torch.empty를 하면 값이 들어있지만 명시적인 값을 포함하지는 않는다. \
즉 당시 메모리에 할당되어 있던 값들이 들어가게 된다.

### 평균 5 표준편차 0.5로 초기화된 8x4 matrix를 만들어 보세요

In [5]:
x = torch.empty(8, 4).normal_(mean=5, std=0.5)

In [6]:
x

tensor([[4.7317, 4.7117, 4.5527, 5.4106],
        [6.1155, 5.4097, 5.1221, 4.2066],
        [4.8529, 5.1549, 5.3147, 5.1168],
        [4.8639, 5.7549, 5.4544, 4.7071],
        [5.0236, 4.5912, 5.0404, 5.8637],
        [4.9814, 5.5602, 5.1657, 5.3097],
        [6.2705, 5.3591, 4.6577, 5.2908],
        [4.9673, 5.0176, 5.5805, 4.9856]])

### 평균 0 표준편차 1로 초기화된 8x4 matrix를 만들어 보세요

In [7]:
x = torch.empty(8, 4).normal_(mean=0, std=1)

In [8]:
x

tensor([[ 0.9341,  2.5844, -0.2361,  2.0010],
        [ 1.5643,  1.3515, -0.3262, -0.5250],
        [-0.9222,  1.0447, -1.9804, -0.0432],
        [-0.5308,  1.8350, -1.6567, -0.4867],
        [-1.0944,  0.8875, -0.5578,  0.3529],
        [-1.1808, -0.8458,  0.0112,  1.1103],
        [-1.6412,  1.1641,  2.7048, -0.7060],
        [ 0.4977, -0.6626, -0.0212,  0.3857]])

### 0으로 초기화된 5x5 matrix를 만들어 보세요

In [10]:
x = torch.zeros(5, 5)

In [11]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

### list [[2,3],[4,4]]를 tensor로 변경해 보세요

In [12]:
x = list([[2, 3], [4, 4]])

In [13]:
type(x)

list

In [14]:
# torch는 tensor 타입만 취급하기 때문에, 데이터 타입을 변환해줘야 한다. 
torch.tensor(x)

tensor([[2, 3],
        [4, 4]])

### 1로 초기화된 7x4 matrix를 만들어 보세요

In [15]:
torch.ones(7, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
torch.ones(7, 4).shape

torch.Size([7, 4])

### torch.randn을 이용하여 float 타입의 5x5 matrix를 만들어 보세요

In [28]:
#torch는 float만 취급한다. int, long, double 모두 안됌
x = torch.randn(5, 5, dtype=torch.float)
x

tensor([[ 0.7283, -0.6850,  1.0123,  0.2610,  0.2827],
        [ 1.7916, -1.3757,  1.3418, -0.8880, -0.5186],
        [ 0.4152,  2.7761,  0.6996,  0.6585, -2.3380],
        [-1.3558, -0.2795, -0.1288, -2.2340,  0.6398],
        [ 0.0163, -0.6967,  2.5402, -0.1937,  1.5511]])

### torch.ones를 이용하여 long 타입의 5x5 mtrix를 만들어 보세요

In [31]:
x = torch.ones(5, 5, dtype=torch.long)
x

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

### torch.randn을 이용하여 [100, 50] 2차원 matrix를 만들어 보세요

In [31]:
x = torch.randn(100, 50)
print(x.shape)

torch.Size([100, 50])


### torch.randn를 이용하여 [100, 50, 20] 3차원 matrix를 만들어 보세요

In [33]:
# 3차원 행렬 만들기
x = torch.randn(3, 2, 2)
x

tensor([[[ 0.3012, -0.8910],
         [-1.0801, -0.8148]],

        [[-0.1711, -0.6487],
         [-0.7736,  0.2895]],

        [[-1.1005,  1.3717],
         [ 1.1470,  0.2506]]])

In [34]:
x = torch.randn(100, 50, 20)
x.shape

torch.Size([100, 50, 20])

### 3차원 matrix에서 추출하기 

In [40]:
x = torch.randn(2, 3, 4)
x[:,:,:]

tensor([[[-1.1112,  1.1703,  1.8353,  0.2039],
         [ 0.3903,  0.5606,  0.7624,  0.6162],
         [-0.0652, -0.6258, -0.7829,  0.6840]],

        [[ 0.5900, -0.6210, -1.1714, -0.4617],
         [-0.0266,  1.1966, -1.0932,  1.3712],
         [-0.5647, -0.3026, -0.0887,  1.6086]]])

In [41]:
x[0,:,:]  # 3 by 4

tensor([[-1.1112,  1.1703,  1.8353,  0.2039],
        [ 0.3903,  0.5606,  0.7624,  0.6162],
        [-0.0652, -0.6258, -0.7829,  0.6840]])

In [42]:
x[:,0,:] # 2 by 4

tensor([[-1.1112,  1.1703,  1.8353,  0.2039],
        [ 0.5900, -0.6210, -1.1714, -0.4617]])

In [43]:
x[:,:,0] # 2 by 3

tensor([[-1.1112,  0.3903, -0.0652],
        [ 0.5900, -0.0266, -0.5647]])

In [44]:
x = torch.randn(100, 50, 20)
x.shape

torch.Size([100, 50, 20])

### 위에서 만든 [100,50,20] matrix로 for문을 이용하여 [100, 20] matrix 50개를 출력해 보세요

In [45]:
for i in range(x.shape[1]):
    print(x[:,i,:].shape)

torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size

### 위에서 만든 [100,50,20]로 for문을 이용하여 [50, 20] matrix 100개를 출력해 보세요

In [46]:
for i in range(x.shape[0]):
    print(x[i,:,:].shape)

torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([5

### 위에서 만든 [100,50,20]로 for문을 이용하여 [100, 50] matrix 20개를 출력해 보세요

In [47]:
for i in range(x.shape[2]):
    print(x[:,:,i].shape)

torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])


### [30, 20] matrx를 만든 후 torch.randn_like를 이용하여 같은 shape의 matrix를 만들어 보세요

In [48]:
x = torch.randn(30, 20)

In [49]:
y = torch.randn_like(x)
print(y.shape)

torch.Size([30, 20])


# operations

In [50]:
x = torch.randn(5, 3)
y = torch.randn(5, 3)

In [51]:
x.shape, y.shape

(torch.Size([5, 3]), torch.Size([5, 3]))

**case 1**

In [52]:
z = x + y
print(z)

tensor([[ 2.5752,  2.5724,  1.5394],
        [ 3.5473,  0.4667,  0.1941],
        [-0.5124,  0.4713,  0.9906],
        [ 1.0779,  1.3367, -0.8016],
        [ 0.4544, -0.3842, -0.6615]])


**case 2**

In [53]:
z = torch.add(x, y)
print(z)

tensor([[ 2.5752,  2.5724,  1.5394],
        [ 3.5473,  0.4667,  0.1941],
        [-0.5124,  0.4713,  0.9906],
        [ 1.0779,  1.3367, -0.8016],
        [ 0.4544, -0.3842, -0.6615]])


**case 3**

In [54]:
z = torch.empty(5, 3)
torch.add(x, y, out=z)

tensor([[ 2.5752,  2.5724,  1.5394],
        [ 3.5473,  0.4667,  0.1941],
        [-0.5124,  0.4713,  0.9906],
        [ 1.0779,  1.3367, -0.8016],
        [ 0.4544, -0.3842, -0.6615]])

In [55]:
z = torch.empty(5, 3)
torch.add(x, y, out=z)
print(z)

tensor([[ 2.5752,  2.5724,  1.5394],
        [ 3.5473,  0.4667,  0.1941],
        [-0.5124,  0.4713,  0.9906],
        [ 1.0779,  1.3367, -0.8016],
        [ 0.4544, -0.3842, -0.6615]])


# Numpy Bridge

개, 고양이 분류모델을 만들었어 -> 정확도를 측정해야해 -> sklearn(acc) -> numpy만 호환

In [56]:
a = torch.randn(3, 4)
print(a.shape)

torch.Size([3, 4])


In [57]:
a.numpy()

array([[ 0.23670216, -0.54023826, -1.2748332 ,  0.67057276],
       [ 0.26735023, -2.0626948 ,  0.48189408,  1.1657482 ],
       [-0.8551174 ,  1.2571824 ,  0.79714423,  0.15328515]],
      dtype=float32)

In [58]:
torch.tensor(a.numpy())

tensor([[ 0.2367, -0.5402, -1.2748,  0.6706],
        [ 0.2674, -2.0627,  0.4819,  1.1657],
        [-0.8551,  1.2572,  0.7971,  0.1533]])

# CUDA 사용하기

GPU를 이용하여 딥러닝을 학습하기 위해서는 데이터를 GPU로 전송해줘야 한다. \
pytorch에서는 간다하게 GPU연산을 할 수 있도록 함수를 제공해준다.

In [59]:
torch.cuda.is_available()

False

In [60]:
device = torch.device('cuda')

In [61]:
x = torch.randn(3, 4)

In [62]:
x.to(device)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx